Mark cdm_vpn_connection output as sensitive
Without this, Terraform 1.0 throws this error:

Error: Output refers to sensitive values

   on outputs.tf line 71:
   71: output "cdm_vpn_connection" {

To reduce the risk of accidentally exporting sensitive data that was 
intended to be only internal, Terraform requires that any root module 
output containing sensitive data be explicitly marked as sensitive, to 
confirm your intent.
 
If you do intend to export this data, annotate the output value as 
sensitive by adding the following argument:
     sensitive = true